TEMPLATEROOT = ..

# compilation flags for gdb

CFLAGS  = -O3 -g3
ASFLAGS = -g3

# object files

OBJS= simple_buffer.o dht22.o stupid_delay.o main.o ssd1306.o ssd1306_fonts.o UART.o $(STARTUP) $(HAL_COMPILE)

# include common make file

include $(TEMPLATEROOT)/Makefile.common
